"""update order status enum and add updated_at column

Revision ID: f5b1db73e438
Revises: d83a7660e7b3
Create Date: 2026-07-03 19:52:01.695640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b1db73e438'
down_revision: Union[str, Sequence[str], None] = 'd83a7660e7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cart_items_user_product', 'cart_items', ['user_id', 'product_id'], unique=False)
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_index('ix_cart_items_user_product', table_name='cart_items')
    # ### end Alembic commands ###
