import moment from 'jalali-moment'

const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹']

export function toPersianNumbers(str: string | number): string {
  return String(str).replace(/\d/g, (d) => persianDigits[parseInt(d)] ?? d)
}

export function formatJalali(dateString: string): string {
  return moment(dateString).locale('fa').format('jYYYY/jMM/jDD')
}

export function formatJalaliDateTime(dateString: string): string {
  return moment(dateString).locale('fa').format('jYYYY/jMM/jDD  HH:mm')
}

export function formatPrice(amount: number): string {
  const formatted = new Intl.NumberFormat('fa-IR').format(amount)
  return `${toPersianNumbers(formatted)} ریال`
}

export const t = {
  nav: {
    products: 'محصولات',
    cart: 'سبد خرید',
    admin: 'مدیریت',
    dashboard: 'داشبورد',
    manageProducts: 'مدیریت محصولات',
    orders: 'سفارشات',
    profile: 'پروفایل',
    myProducts: 'محصولات من',
  },
  auth: {
    loginTitle: 'بازارچه عتیقه',
    loginSubtitle: 'به حساب خود وارد شوید',
    username: 'نام کاربری',
    usernamePlaceholder: 'نام کاربری خود را وارد کنید',
    password: 'رمز عبور',
    passwordPlaceholder: 'رمز عبور خود را وارد کنید',
    rememberMe: 'مرا به خاطر بسپار',
    signIn: 'ورود',
    logout: 'خروج',
    welcomeBack: 'خوش آمدید!',
    loginFailed: 'خطا در ورود',
    registerTitle: 'ایجاد حساب کاربری',
    registerSubtitle: 'حساب جدیدی بسازید',
    signUp: 'ثبت نام',
    noAccount: 'حساب کاربری ندارید؟',
    hasAccount: 'قبلاً ثبت نام کرده‌اید؟',
    confirmPassword: 'تأیید رمز عبور',
    registerSuccess: 'ثبت نام با موفقیت انجام شد',
    registerFailed: 'خطا در ثبت نام',
    passwordMismatch: 'رمز عبور و تأیید آن مطابقت ندارند',
  },
  products: {
    title: 'محصولات',
    subtitle: 'مجموعه عتیقه‌های ما را مرور کنید',
    search: 'جستجوی محصولات...',
    filters: 'فیلترها',
    category: 'دسته‌بندی',
    allCategories: 'همه دسته‌بندی‌ها',
    minPrice: 'حداقل قیمت',
    maxPrice: 'حداکثر قیمت',
    status: 'وضعیت',
    active: 'فعال',
    inactive: 'غیرفعال',
    all: 'همه',
    minStock: 'حداقل موجودی',
    maxStock: 'حداکثر موجودی',
    sortBy: 'مرتب‌سازی بر اساس',
    dateCreated: 'تاریخ ایجاد',
    price: 'قیمت',
    name: 'نام',
    ascending: 'صعودی',
    descending: 'نزولی',
    product: 'محصول',
    sku: 'کد کالا',
    categoryLabel: 'دسته‌بندی',
    priceLabel: 'قیمت',
    statusLabel: 'وضعیت',
    noImage: 'بدون تصویر',
    noProducts: 'محصولی یافت نشد',
    showing: 'نمایش',
    to: 'تا',
    from: 'از',
    results: 'نتیجه',
    page: 'صفحه',
    of: 'از',
    addToCart: 'افزودن به سبد خرید',
    viewDetails: 'مشاهده جزئیات',
    description: 'توضیحات',
    seller: 'فروشنده',
    stock: 'موجودی',
    inStock: 'موجود',
    outOfStock: 'ناموجود',
    backToProducts: 'بازگشت به محصولات',
    myProducts: 'محصولات من',
  },
  admin: {
    dashboardTitle: 'داشبورد مدیریت',
    dashboardSubtitle: 'نمای کلی بازارچه شما',
    totalProducts: 'کل محصولات',
    activeProducts: 'محصولات فعال',
    categories: 'دسته‌بندی‌ها',
    totalValue: 'ارزش کل',
    manageTitle: 'مدیریت محصولات',
    manageSubtitle: 'ایجاد، ویرایش و حذف محصولات',
    addProduct: 'افزودن محصول',
    editProduct: 'ویرایش محصول',
    createProduct: 'ایجاد محصول',
    deleteProduct: 'حذف محصول',
    deleteConfirm: 'آیا از حذف این محصول اطمینان دارید؟ این عمل قابل بازگشت نیست.',
    title: 'عنوان',
    titlePlaceholder: 'عنوان محصول',
    description: 'توضیحات',
    descriptionPlaceholder: 'توضیحات محصول',
    skuLabel: 'کد کالا',
    skuPlaceholder: 'کد-۰۰۱',
    priceLabel: 'قیمت',
    quantity: 'تعداد',
    categoryLabel: 'دسته‌بندی',
    sellerId: 'شناسه فروشنده',
    activeLabel: 'فعال',
    cancel: 'انصراف',
    create: 'ایجاد',
    update: 'به‌روزرسانی',
    delete: 'حذف',
    productCreated: 'محصول با موفقیت ایجاد شد',
    productUpdated: 'محصول با موفقیت به‌روزرسانی شد',
    productDeleted: 'محصول با موفقیت حذف شد',
    createFailed: 'خطا در ایجاد محصول',
    updateFailed: 'خطا در به‌روزرسانی محصول',
    deleteFailed: 'خطا در حذف محصول',
    images: 'تصاویر',
    selectImages: 'انتخاب تصاویر',
    imageUploaded: 'تصویر با موفقیت آپلود شد',
    imageUploadFailed: 'خطا در آپلود تصویر',
    imageDeleted: 'تصویر با موفقیت حذف شد',
    imageDeleteFailed: 'خطا در حذف تصویر',
    stock: 'موجودی',
    actions: 'عملیات',
    // User management
    manageUsers: 'مدیریت کاربران',
    manageUsersSubtitle: 'مشاهده و مدیریت کاربران سیستم',
    user: 'کاربر',
    role: 'نقش',
    status: 'وضعیت',
    joinDate: 'تاریخ عضویت',
    active: 'فعال',
    banned: 'مسدود',
    ban: 'مسدود کردن',
    unban: 'رفع مسدودیت',
    changeRole: 'تغییر نقش',
    userRoleUpdated: 'نقش کاربر با موفقیت تغییر کرد',
    userBanned: 'کاربر با موفقیت مسدود شد',
    userUnbanned: 'مسدودیت کاربر با موفقیت رفع شد',
    roleUpdateFailed: 'خطا در تغییر نقش کاربر',
    banFailed: 'خطا در مسدود کردن کاربر',
    unbanFailed: 'خطا در رفع مسدودیت کاربر',
    confirmBan: 'آیا از مسدود کردن این کاربر اطمینان دارید؟',
    confirmUnban: 'آیا از رفع مسدودیت این کاربر اطمینان دارید؟',
    noUsers: 'هیچ کاربری یافت نشد',
    userRole: 'نقش کاربر',
    adminRole: 'مدیر',
  },
  validation: {
    required: 'این فیلد الزامی است',
    positivePrice: 'قیمت باید مثبت باشد',
    positiveQuantity: 'تعداد باید مثبت باشد',
  },
  notFound: {
    title: '۴۰۴',
    message: 'صفحه مورد نظر یافت نشد',
    description: 'صفحه‌ای که به دنبال آن هستید وجود ندارد یا منتقل شده است.',
    backToHome: 'بازگشت به صفحه اصلی',
  },
  cart: {
    title: 'سبد خرید',
    empty: 'سبد خرید شما خالی است',
    browseProducts: 'مشاهده محصولات',
    total: 'جمع کل',
    quantity: 'تعداد',
    remove: 'حذف',
    clearCart: 'خالی کردن سبد',
    checkout: 'تسویه حساب',
    itemAdded: 'محصول به سبد اضافه شد',
    itemRemoved: 'محصول از سبد حذف شد',
    cartCleared: 'سبد خرید خالی شد',
    addToCartFailed: 'خطا در افزودن به سبد',
    updateFailed: 'خطا در بروزرسانی سبد',
    removeFailed: 'خطا در حذف از سبد',
    insufficientStock: 'موجودی کافی نیست',
  },
  orders: {
    title: 'سفارشات',
    empty: 'شما هنوز سفارشی ثبت نکرده‌اید',
    orderNumber: 'شماره سفارش',
    date: 'تاریخ',
    status: 'وضعیت',
    total: 'مبلغ کل',
    items: 'اقلام',
    pending: 'در انتظار',
    confirmed: 'تأیید شده',
    shipped: 'ارسال شده',
    delivered: 'تحویل شده',
    cancelled: 'لغو شده',
    createSuccess: 'سفارش با موفقیت ثبت شد',
    createFailed: 'خطا در ثبت سفارش',
    cancelOrder: 'لغو سفارش',
    cancelConfirm: 'آیا از لغو این سفارش اطمینان دارید؟',
    cancelSuccess: 'سفارش با موفقیت لغو شد',
    cancelFailed: 'خطا در لغو سفارش',
    viewDetails: 'جزئیات سفارش',
  },
  profile: {
    title: 'پروفایل',
    changePassword: 'تغییر رمز عبور',
    currentPassword: 'رمز عبور فعلی',
    newPassword: 'رمز عبور جدید',
    confirmPassword: 'تأیید رمز عبور',
    updatePassword: 'بروزرسانی رمز',
    passwordChanged: 'رمز عبور با موفقیت تغییر کرد',
    passwordChangeFailed: 'خطا در تغییر رمز عبور',
    memberSince: 'عضویت از',
  },
  common: {
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    save: 'ذخیره',
    edit: 'ویرایش',
    delete: 'حذف',
    confirm: 'تأیید',
    cancel: 'انصراف',
    success: 'موفقیت',
    retry: 'تلاش مجدد',
    back: 'بازگشت',
  },
  layout: {
    marketplace: 'بازارچه',
    admin: 'مدیریت',
  },
}
